# Generated by Django 3.2.2 on 2021-05-10 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=200, null=True)),
                ('telefono', models.CharField(default='', max_length=200, null=True)),
                ('correo', models.CharField(default='', max_length=200, null=True)),
                ('edad', models.CharField(default='', max_length=200, null=True)),
                ('educacion', models.TextField(default='', max_length=200, null=True)),
                ('experiencia', models.TextField(default='', max_length=200, null=True)),
                ('aptitudes', models.TextField(default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituto', models.TextField(default='', max_length=200, null=True)),
                ('nombre', models.TextField(default='', max_length=200, null=True)),
                ('historia', models.CharField(default='', max_length=200, null=True)),
                ('eventos', models.CharField(default='', max_length=200, null=True)),
            ],
        ),
    ]
